
package com.currencycloud.sdk.model;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;


/**
 * SimulateFunding
 */
@JsonDeserialize(builder = SimulateFunding.Builder.class)
public final class SimulateFunding {
    /**
     * The account UUID the simulated fund was created for.
     */
    private final String accountId;

    /**
     * Allows you to trigger approval or rejection behaviour.
     */
    private final SimulateFundingActionEnum action;

    /**
     * Amount of the emulated transaction.
     */
    private final String amount;

    /**
     * The date-time the SSI was added to the account.
     */
    private final String createdAt;

    /**
     * Three-digit currency code.
     */
    private final String currency;

    /**
     * The unique UUID for the simulated fund.
     */
    private final String id;

    /**
     * A client or its sub-account's account number.
     */
    private final String receiverAccountNumber;

    /**
     * Routing code for a client or its sub-account.
     */
    private final String receiverRoutingCode;

    /**
     * Sender account number.
     */
    private final String senderAccountNumber;

    /**
     * The sender's address.
     */
    private final String senderAddress;

    /**
     * Two-digit sender country.
     */
    private final String senderCountry;

    /**
     * The sender's name.
     */
    private final String senderName;

    /**
     * Sender reference.
     */
    private final String senderReference;

    /**
     * Sender routing code.
     */
    private final String senderRoutingCode;

    /**
     * The reference generated by the system to identify the fund.
     */
    private final String shortReference;

    /**
     * The state of the simulated fund.
     */
    private final String state;

    /**
     * The date-time the SSI was last updated on the account.
     */
    private final String updatedAt;

    private final Map<String, Object> additionalProperties;


    private SimulateFunding(Builder builder) {
        this.accountId = builder.accountId;
        this.action = builder.action;
        this.amount = builder.amount;
        this.createdAt = builder.createdAt;
        this.currency = builder.currency;
        this.id = builder.id;
        this.receiverAccountNumber = builder.receiverAccountNumber;
        this.receiverRoutingCode = builder.receiverRoutingCode;
        this.senderAccountNumber = builder.senderAccountNumber;
        this.senderAddress = builder.senderAddress;
        this.senderCountry = builder.senderCountry;
        this.senderName = builder.senderName;
        this.senderReference = builder.senderReference;
        this.senderRoutingCode = builder.senderRoutingCode;
        this.shortReference = builder.shortReference;
        this.state = builder.state;
        this.updatedAt = builder.updatedAt;
        this.additionalProperties = builder.additionalProperties;
    }

    /**
     * Retrieves value for `accountId`
     * The account UUID the simulated fund was created for.
     */
    @JsonProperty("account_id")
    public String getAccountId() {
        return accountId;
    }
    /**
     * Retrieves value for `action`
     * Allows you to trigger approval or rejection behaviour.
     */
    @JsonProperty("action")
    public SimulateFundingActionEnum getAction() {
        return action;
    }
    /**
     * Retrieves value for `amount`
     * Amount of the emulated transaction.
     */
    @JsonProperty("amount")
    public String getAmount() {
        return amount;
    }
    /**
     * Retrieves value for `createdAt`
     * The date-time the SSI was added to the account.
     */
    @JsonProperty("created_at")
    public String getCreatedAt() {
        return createdAt;
    }
    /**
     * Retrieves value for `currency`
     * Three-digit currency code.
     */
    @JsonProperty("currency")
    public String getCurrency() {
        return currency;
    }
    /**
     * Retrieves value for `id`
     * The unique UUID for the simulated fund.
     */
    @JsonProperty("id")
    public String getId() {
        return id;
    }
    /**
     * Retrieves value for `receiverAccountNumber`
     * A client or its sub-account's account number.
     */
    @JsonProperty("receiver_account_number")
    public String getReceiverAccountNumber() {
        return receiverAccountNumber;
    }
    /**
     * Retrieves value for `receiverRoutingCode`
     * Routing code for a client or its sub-account.
     */
    @JsonProperty("receiver_routing_code")
    public String getReceiverRoutingCode() {
        return receiverRoutingCode;
    }
    /**
     * Retrieves value for `senderAccountNumber`
     * Sender account number.
     */
    @JsonProperty("sender_account_number")
    public String getSenderAccountNumber() {
        return senderAccountNumber;
    }
    /**
     * Retrieves value for `senderAddress`
     * The sender's address.
     */
    @JsonProperty("sender_address")
    public String getSenderAddress() {
        return senderAddress;
    }
    /**
     * Retrieves value for `senderCountry`
     * Two-digit sender country.
     */
    @JsonProperty("sender_country")
    public String getSenderCountry() {
        return senderCountry;
    }
    /**
     * Retrieves value for `senderName`
     * The sender's name.
     */
    @JsonProperty("sender_name")
    public String getSenderName() {
        return senderName;
    }
    /**
     * Retrieves value for `senderReference`
     * Sender reference.
     */
    @JsonProperty("sender_reference")
    public String getSenderReference() {
        return senderReference;
    }
    /**
     * Retrieves value for `senderRoutingCode`
     * Sender routing code.
     */
    @JsonProperty("sender_routing_code")
    public String getSenderRoutingCode() {
        return senderRoutingCode;
    }
    /**
     * Retrieves value for `shortReference`
     * The reference generated by the system to identify the fund.
     */
    @JsonProperty("short_reference")
    public String getShortReference() {
        return shortReference;
    }
    /**
     * Retrieves value for `state`
     * The state of the simulated fund.
     */
    @JsonProperty("state")
    public String getState() {
        return state;
    }
    /**
     * Retrieves value for `updatedAt`
     * The date-time the SSI was last updated on the account.
     */
    @JsonProperty("updated_at")
    public String getUpdatedAt() {
        return updatedAt;
    }
    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) { return true; }

        return other instanceof SimulateFunding && equalTo((SimulateFunding) other);
    }

    private boolean equalTo(SimulateFunding other) {
        return
            accountId.equals(other.accountId) &&

            action.equals(other.action) &&

            amount.equals(other.amount) &&

            createdAt.equals(other.createdAt) &&

            currency.equals(other.currency) &&

            id.equals(other.id) &&

            receiverAccountNumber.equals(other.receiverAccountNumber) &&

            receiverRoutingCode.equals(other.receiverRoutingCode) &&

            senderAccountNumber.equals(other.senderAccountNumber) &&

            senderAddress.equals(other.senderAddress) &&

            senderCountry.equals(other.senderCountry) &&

            senderName.equals(other.senderName) &&

            senderReference.equals(other.senderReference) &&

            senderRoutingCode.equals(other.senderRoutingCode) &&

            shortReference.equals(other.shortReference) &&

            state.equals(other.state) &&

            updatedAt.equals(other.updatedAt)
            &&
            additionalProperties.equals(other.additionalProperties)
            ;
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                   this.accountId,
                   this.action,
                   this.amount,
                   this.createdAt,
                   this.currency,
                   this.id,
                   this.receiverAccountNumber,
                   this.receiverRoutingCode,
                   this.senderAccountNumber,
                   this.senderAddress,
                   this.senderCountry,
                   this.senderName,
                   this.senderReference,
                   this.senderRoutingCode,
                   this.shortReference,
                   this.state,
                   this.updatedAt
                   ,
                   this.additionalProperties
               );
    }

    @Override
    public String toString() {
        return "SimulateFunding{" +
               "accountId=" + accountId + ", " +
               "action=" + action + ", " +
               "amount=" + amount + ", " +
               "createdAt=" + createdAt + ", " +
               "currency=" + currency + ", " +
               "id=" + id + ", " +
               "receiverAccountNumber=" + receiverAccountNumber + ", " +
               "receiverRoutingCode=" + receiverRoutingCode + ", " +
               "senderAccountNumber=" + senderAccountNumber + ", " +
               "senderAddress=" + senderAddress + ", " +
               "senderCountry=" + senderCountry + ", " +
               "senderName=" + senderName + ", " +
               "senderReference=" + senderReference + ", " +
               "senderRoutingCode=" + senderRoutingCode + ", " +
               "shortReference=" + shortReference + ", " +
               "state=" + state + ", " +
               "updatedAt=" + updatedAt +
               ", additionalProperties=" + additionalProperties +
               '}';
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        /**
         * The account UUID the simulated fund was created for.
         */
        private String accountId = null;

        /**
         * Allows you to trigger approval or rejection behaviour.
         */
        private SimulateFundingActionEnum action = null;

        /**
         * Amount of the emulated transaction.
         */
        private String amount = null;

        /**
         * The date-time the SSI was added to the account.
         */
        private String createdAt = null;

        /**
         * Three-digit currency code.
         */
        private String currency = null;

        /**
         * The unique UUID for the simulated fund.
         */
        private String id = null;

        /**
         * A client or its sub-account's account number.
         */
        private String receiverAccountNumber = null;

        /**
         * Routing code for a client or its sub-account.
         */
        private String receiverRoutingCode = null;

        /**
         * Sender account number.
         */
        private String senderAccountNumber = null;

        /**
         * The sender's address.
         */
        private String senderAddress = null;

        /**
         * Two-digit sender country.
         */
        private String senderCountry = null;

        /**
         * The sender's name.
         */
        private String senderName = null;

        /**
         * Sender reference.
         */
        private String senderReference = null;

        /**
         * Sender routing code.
         */
        private String senderRoutingCode = null;

        /**
         * The reference generated by the system to identify the fund.
         */
        private String shortReference = null;

        /**
         * The state of the simulated fund.
         */
        private String state = null;

        /**
         * The date-time the SSI was last updated on the account.
         */
        private String updatedAt = null;

        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(SimulateFunding other) {
            accountId(other.getAccountId());
            action(other.getAction());
            amount(other.getAmount());
            createdAt(other.getCreatedAt());
            currency(other.getCurrency());
            id(other.getId());
            receiverAccountNumber(other.getReceiverAccountNumber());
            receiverRoutingCode(other.getReceiverRoutingCode());
            senderAccountNumber(other.getSenderAccountNumber());
            senderAddress(other.getSenderAddress());
            senderCountry(other.getSenderCountry());
            senderName(other.getSenderName());
            senderReference(other.getSenderReference());
            senderRoutingCode(other.getSenderRoutingCode());
            shortReference(other.getShortReference());
            state(other.getState());
            updatedAt(other.getUpdatedAt());
            additionalProperties(other.getAdditionalProperties());
            return this;
        }

        /**
         * Sets value for `accountId`
         * The account UUID the simulated fund was created for.
         */
        @JsonSetter("account_id")
        public Builder accountId(String accountId) {
            if (accountId == null) {
                throw new IllegalArgumentException("accountId cannot be null");
            }

            this.accountId = accountId;
            return this;
        }
        /**
         * Sets value for `action`
         * Allows you to trigger approval or rejection behaviour.
         */
        @JsonSetter("action")
        public Builder action(SimulateFundingActionEnum action) {
            if (action == null) {
                throw new IllegalArgumentException("action cannot be null");
            }

            this.action = action;
            return this;
        }
        /**
         * Sets value for `amount`
         * Amount of the emulated transaction.
         */
        @JsonSetter("amount")
        public Builder amount(String amount) {
            if (amount == null) {
                throw new IllegalArgumentException("amount cannot be null");
            }

            this.amount = amount;
            return this;
        }
        /**
         * Sets value for `createdAt`
         * The date-time the SSI was added to the account.
         */
        @JsonSetter("created_at")
        public Builder createdAt(String createdAt) {
            if (createdAt == null) {
                throw new IllegalArgumentException("createdAt cannot be null");
            }

            this.createdAt = createdAt;
            return this;
        }
        /**
         * Sets value for `currency`
         * Three-digit currency code.
         */
        @JsonSetter("currency")
        public Builder currency(String currency) {
            if (currency == null) {
                throw new IllegalArgumentException("currency cannot be null");
            }

            this.currency = currency;
            return this;
        }
        /**
         * Sets value for `id`
         * The unique UUID for the simulated fund.
         */
        @JsonSetter("id")
        public Builder id(String id) {
            if (id == null) {
                throw new IllegalArgumentException("id cannot be null");
            }

            this.id = id;
            return this;
        }
        /**
         * Sets value for `receiverAccountNumber`
         * A client or its sub-account's account number.
         */
        @JsonSetter("receiver_account_number")
        public Builder receiverAccountNumber(String receiverAccountNumber) {
            if (receiverAccountNumber == null) {
                throw new IllegalArgumentException("receiverAccountNumber cannot be null");
            }

            this.receiverAccountNumber = receiverAccountNumber;
            return this;
        }
        /**
         * Sets value for `receiverRoutingCode`
         * Routing code for a client or its sub-account.
         */
        @JsonSetter("receiver_routing_code")
        public Builder receiverRoutingCode(String receiverRoutingCode) {
            if (receiverRoutingCode == null) {
                throw new IllegalArgumentException("receiverRoutingCode cannot be null");
            }

            this.receiverRoutingCode = receiverRoutingCode;
            return this;
        }
        /**
         * Sets value for `senderAccountNumber`
         * Sender account number.
         */
        @JsonSetter("sender_account_number")
        public Builder senderAccountNumber(String senderAccountNumber) {
            if (senderAccountNumber == null) {
                throw new IllegalArgumentException("senderAccountNumber cannot be null");
            }

            this.senderAccountNumber = senderAccountNumber;
            return this;
        }
        /**
         * Sets value for `senderAddress`
         * The sender's address.
         */
        @JsonSetter("sender_address")
        public Builder senderAddress(String senderAddress) {
            if (senderAddress == null) {
                throw new IllegalArgumentException("senderAddress cannot be null");
            }

            this.senderAddress = senderAddress;
            return this;
        }
        /**
         * Sets value for `senderCountry`
         * Two-digit sender country.
         */
        @JsonSetter("sender_country")
        public Builder senderCountry(String senderCountry) {
            if (senderCountry == null) {
                throw new IllegalArgumentException("senderCountry cannot be null");
            }

            this.senderCountry = senderCountry;
            return this;
        }
        /**
         * Sets value for `senderName`
         * The sender's name.
         */
        @JsonSetter("sender_name")
        public Builder senderName(String senderName) {
            if (senderName == null) {
                throw new IllegalArgumentException("senderName cannot be null");
            }

            this.senderName = senderName;
            return this;
        }
        /**
         * Sets value for `senderReference`
         * Sender reference.
         */
        @JsonSetter("sender_reference")
        public Builder senderReference(String senderReference) {
            if (senderReference == null) {
                throw new IllegalArgumentException("senderReference cannot be null");
            }

            this.senderReference = senderReference;
            return this;
        }
        /**
         * Sets value for `senderRoutingCode`
         * Sender routing code.
         */
        @JsonSetter("sender_routing_code")
        public Builder senderRoutingCode(String senderRoutingCode) {
            if (senderRoutingCode == null) {
                throw new IllegalArgumentException("senderRoutingCode cannot be null");
            }

            this.senderRoutingCode = senderRoutingCode;
            return this;
        }
        /**
         * Sets value for `shortReference`
         * The reference generated by the system to identify the fund.
         */
        @JsonSetter("short_reference")
        public Builder shortReference(String shortReference) {
            if (shortReference == null) {
                throw new IllegalArgumentException("shortReference cannot be null");
            }

            this.shortReference = shortReference;
            return this;
        }
        /**
         * Sets value for `state`
         * The state of the simulated fund.
         */
        @JsonSetter("state")
        public Builder state(String state) {
            if (state == null) {
                throw new IllegalArgumentException("state cannot be null");
            }

            this.state = state;
            return this;
        }
        /**
         * Sets value for `updatedAt`
         * The date-time the SSI was last updated on the account.
         */
        @JsonSetter("updated_at")
        public Builder updatedAt(String updatedAt) {
            if (updatedAt == null) {
                throw new IllegalArgumentException("updatedAt cannot be null");
            }

            this.updatedAt = updatedAt;
            return this;
        }

        @JsonAnySetter
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }



        public SimulateFunding build() {
            if (accountId == null) {
                throw new IllegalStateException("accountId is required");
            }

            if (action == null) {
                throw new IllegalStateException("action is required");
            }

            if (amount == null) {
                throw new IllegalStateException("amount is required");
            }

            if (createdAt == null) {
                throw new IllegalStateException("createdAt is required");
            }

            if (currency == null) {
                throw new IllegalStateException("currency is required");
            }

            if (id == null) {
                throw new IllegalStateException("id is required");
            }

            if (receiverAccountNumber == null) {
                throw new IllegalStateException("receiverAccountNumber is required");
            }

            if (receiverRoutingCode == null) {
                throw new IllegalStateException("receiverRoutingCode is required");
            }

            if (senderAccountNumber == null) {
                throw new IllegalStateException("senderAccountNumber is required");
            }

            if (senderAddress == null) {
                throw new IllegalStateException("senderAddress is required");
            }

            if (senderCountry == null) {
                throw new IllegalStateException("senderCountry is required");
            }

            if (senderName == null) {
                throw new IllegalStateException("senderName is required");
            }

            if (senderReference == null) {
                throw new IllegalStateException("senderReference is required");
            }

            if (senderRoutingCode == null) {
                throw new IllegalStateException("senderRoutingCode is required");
            }

            if (shortReference == null) {
                throw new IllegalStateException("shortReference is required");
            }

            if (state == null) {
                throw new IllegalStateException("state is required");
            }

            if (updatedAt == null) {
                throw new IllegalStateException("updatedAt is required");
            }

            return new SimulateFunding(this);
        }
    }

}



